### ISSUE TITLE
Axolotl-related recipes in 1.16.5

### ISSUE THREAD

**Issue by JuergenSchT** [StevePlayzz/Skinned-Lanterns-Fabric#1]
Skinned Lanterns version: 1.1.3
On client/server load, Skinned Lantern tries to register four Axolotl-related recipes. This fails, spitting a bunch of errors in the log. The mod still works fine, with singleplayer/multiplayer worlds loading normally, but some players might consider this a nuisance.
[[sample server log]](https://gist.github.com/JuergenSchT/8d662bb3192f3aee66e728f0283b093a)

**Comment by Steven-Baez** [comment]
Fixed in the latest commit
