### ISSUE TITLE
[1.18.x] Lantern's don't drop when broken with a pickaxe

### ISSUE THREAD

**Issue by Joulanh** [StevePlayzz/Skinned-Lanterns-Fabric#11]
[1.18.1] Lanterns take very long to break even with a pickaxe and drop no items when destroyed

**Comment by DJMan255** [comment]
Having the exact same issue.

**Comment by ChielTheOread** [comment]
Having the exact same issue

**Comment by Cooliosity** [comment]
Having the exact same issue on Fabric 1.18.1

**Comment by ValynnVisalle** [comment]
I am having the same issue. I think the reason is that they don't have a loot table attached to them. (I have REI so I can see the crafting and item info.)

**Comment by Steven-Baez** [comment]
they do, just that they don't have a tag that they added in 1.18 which makes it breakable with a pick

**Comment by Steven-Baez** [comment]
oh shoot you're right, I forgot to change the loot tables modid since I changed it sorry guys
