### ISSUE TITLE
Crash on newer versions of Fabric with something you are bundling in your jar

### ISSUE THREAD

**Issue by Sunconure11** [StevePlayzz/Skinned-Lanterns-Fabric#15]
https://pastebin.com/BXA3pXNP

@stevendevs

**Comment by Steven-Baez** [comment]
Try this https://github.com/Evoslab/skinned-lanterns/suites/6141683633/artifacts/214283088

**Comment by Sunconure11** [comment]
Will try now, was busting another a bug that manifested when this showed up

**Comment by Sunconure11** [comment]
Mod calls for Pollen and the latest build is not compatible with 1.18.2

**Comment by Sunconure11** [comment]
![image](https://user-images.githubusercontent.com/5614902/165537564-a9f740bf-c4f3-4c67-b7e7-29c29392809b.png)

**Comment by Sunconure11** [comment]
Wait, @stevendevs, your build is for 1.18.1. I was using the build marked as 1.18.2 compatible but it would seem this is not the case.

https://www.curseforge.com/minecraft/mc-mods/skinned-lanterns-fabric/files/3586429

**Comment by Steven-Baez** [comment]
It was supposed to work with 1.18.2 but that's not the case

**Comment by Steven-Baez** [comment]
yeah sorry about that, was on my part
