### ISSUE TITLE
Do not load lanterns for items that are not found

### ISSUE THREAD

**Issue by itsNordLord** [StevePlayzz/Skinned-Lanterns-Fabric#2]
Log: https://paste.gg/p/anonymous/c4846deedd6b4bc4a20fe5e1f34c9e93

This mod spits out 350+ console lines on every startup attempting to load lanterns for blocks that dont exist, namely Axolotls like in #1, but also Lil Taters. 

Check if Lil Tater is loaded before attempting to create whatever requires Lil Tater, same for Axolotls.

**Comment by Steven-Baez** [comment]
Should be fixed in the latest commit
