### ISSUE TITLE
Game Crashes on Client 1.17 Launch

### ISSUE THREAD

**Issue by kalinzange** [StevePlayzz/Skinned-Lanterns-Fabric#4]
Crash Report Below:

[skinnedlaterns-crash-2021-06-19_23.28.20-client.txt](https://github.com/StevePlayzz/Skinned-Lanterns-Fabric/files/6683103/skinnedlaterns-crash-2021-06-19_23.28.20-client.txt)

I'm not sure if it's because Auto Config API isn't updated yet for 1.17

**Comment by Poyoraz** [comment]
I don't think the mod is updated to 1.17 main release yet

**Comment by Steven-Baez** [comment]
Fixed in the latest commit
