### ISSUE TITLE
Lanterns always face south regardless of direction faced when placed

### ISSUE THREAD

**Issue by shaneknysh** [StevePlayzz/Skinned-Lanterns-Fabric#9]
Lanterns always face south when placed  - ie the front of a lantern will not be seen if placed on the north side of a block.

versions
skinned lanterns 1.1.5
fabric 0.74
minecraft 1.17.1

screen shots:

![2021-10-25_11 23 37-cropped](https://user-images.githubusercontent.com/158361/138744424-82253a32-cfa8-42ba-99e9-db521182fe1b.png)

![2021-10-25_11 23 44-cropped](https://user-images.githubusercontent.com/158361/138744429-255fc0b2-a841-40df-89c9-96b94aef0e71.png)

**Comment by Steven-Baez** [comment]
do you have any other mods?

**Comment by shaneknysh** [comment]
Yes, I will try and test for isolation but it might take a few ~days~ hours. 

I will update as I test
[x] architectury-2.5.27-fabric.jar
[x] bedspreads-fabric-1.4.0-1.17.jar
[x] cloth-config-5.0.38-fabric.jar
[x] Croptopia-1.17.1-FABRIC-1.6.3.jar
[x] expandedstorage-7.2.7+1.17.1.jar
[x] FallingTree-1.17.1-2.14.0.jar
[x] full-slabs-3.2.0.jar
[x] Harvest-fabric-1.16.1-1.0.1.jar
[ ] modmenu-2.0.11.jar
[x] ninjaphenix-container-library-1.2.4+1.17.1.jar
[x] Patchouli-1.16.4-53.2.jar
[x] RoughlyEnoughItems-6.0.279-alpha-fabric.jar
[ ] skinnedlanterns-1.1.5.jar
[x] torohealth-1.17.1-fabric-12.jar
[x] worldedit-mod-7.2.6.jar
[x] Xaeros_Minimap_21.16.0_Fabric_1.17.1.jar
[x] XaerosWorldMap_1.17.0_Fabric_1.17.1.jar

retested with just skinned lanterns and mod menu
![2021-10-25_22 08 23](https://user-images.githubusercontent.com/158361/138807475-36878aa1-9cda-4cd4-931d-2219c5c963fb.png)

**Comment by Steven-Baez** [comment]
did you find out what was causing this?

**Comment by Steven-Baez** [comment]
nvm im fixing it now
